---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Template Nginx configuration for ChocoMap
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/chocomap
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Enable ChocoMap site
  file:
    src: /etc/nginx/sites-available/chocomap
    dest: /etc/nginx/sites-enabled/chocomap
    state: link
  notify: reload nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Test Nginx configuration
  command: nginx -t
  changed_when: false

- name: Ensure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
