---
- name: Install MySQL server and client
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present

- name: Ensure MySQL service is running and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
