"""initial migration

Revision ID: 7f25ca47ac0b
Revises: 
Create Date: 2025-05-19 21:30:12.033368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f25ca47ac0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    op.drop_table('addresses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.ENUM('driver', 'employee', 'manager'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('addresses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('label', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('street_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('zip_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('latitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('longitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='addresses_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('deliveries',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('driver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('delivery_date', sa.DATE(), nullable=True),
    sa.Column('start_time', mysql.TIME(), nullable=True),
    sa.Column('end_time', mysql.TIME(), nullable=True),
    sa.Column('assigned_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'accepted', 'rejected', 'done'), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('eta_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('return_eta_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name='deliveries_ibfk_2'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name='deliveries_ibfk_3'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name='deliveries_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
